const data = require("../services/dataService");
const { createId } = require("../utils/ids");
const HttpError = require("../utils/httpError");
const { publicUser } = require("./authController");

const taskStatuses = ["TODO", "IN_PROGRESS", "DONE", "AWAITING_REVIEW", "APPROVED", "CHANGES_REQUESTED"];
const teamRoles = ["Frontend Developer", "Backend Developer", "Full-Stack Developer", "Mobile Developer", "UI/UX Designer", "Product Designer", "Team Lead", "Project Manager", "Product Manager", "QA Engineer", "DevOps Engineer", "Data Analyst", "Data Scientist", "Machine Learning Engineer", "Security Engineer", "Database Administrator", "Software Architect", "Business Analyst", "Scrum Master", "Technical Writer", "Custom Role"];
const legacyStatus = { "To Do": "TODO", "In Progress": "IN_PROGRESS", Review: "AWAITING_REVIEW", Done: "DONE" };
function status(value) { const normalized = String(value || "").toUpperCase().replaceAll(" ", "_"); return legacyStatus[value] || (taskStatuses.includes(normalized) ? normalized : null); }
function send(response, dataValue, statusCode = 200) { response.status(statusCode).json({ success: true, data: dataValue }); }
function requireRecord(collection, id, companyId) { const record = data.get(collection, id, companyId); if (!record) throw new HttpError(404, `${collection.slice(0, -1)} not found`); return record; }
function assertEmployer(request) { if (request.user.role !== "employer") throw new HttpError(403, "Employer access required"); }
function visible(collection, request, predicate) { const records = data.list(collection, request.user.companyId, predicate); return request.user.role === "employee" ? records.filter((record) => record.assignedEmployeeId === request.user.id || record.assigneeId === request.user.id || record.employeeId === request.user.id || record.memberIds?.includes(request.user.id) || record.participants?.includes(request.user.id)) : records; }
function calculateProject(project, companyId) { const tasks = data.list("tasks", companyId, (task) => task.projectId === project.id); const count = (values) => tasks.filter((task) => values.includes(task.status)).length; const total = tasks.length; return { ...project, statistics: { total, completed: count(["DONE", "APPROVED"]), remaining: count(["TODO", "CHANGES_REQUESTED"]), inProgress: count(["IN_PROGRESS"]), awaitingReview: count(["AWAITING_REVIEW"]), approved: count(["APPROVED"]), completionPercentage: total ? Math.round(count(["DONE", "APPROVED"]) / total * 100) : 0 } }; }
function calculateTeam(team, companyId) { const employees = data.list("users", companyId, (user) => user.role === "employee" && (team.memberIds || []).includes(user.id)); const tasks = data.list("tasks", companyId); return { ...team, members: employees.map((employee) => { const assigned = tasks.filter((task) => task.assignedEmployeeId === employee.id || task.assigneeId === employee.id); const completed = assigned.filter((task) => ["DONE", "APPROVED"].includes(task.status)).length; return { ...publicUser(employee), assignedTasks: assigned.length, completedTasks: completed, remainingTasks: assigned.length - completed, completionPercentage: assigned.length ? Math.round(completed / assigned.length * 100) : 0, role: team.memberRoles?.[employee.id] || "Member" }; }) }; }
function createNotification(companyId, values) { const duplicate = data.findOne("notifications", (item) => item.companyId === companyId && item.recipientId === values.recipientId && item.relatedTaskId === values.relatedTaskId && item.type === values.type && item.message === values.message); return duplicate || data.insert("notifications", { companyId, ...values, id: createId("notification"), read: false, createdAt: new Date().toISOString() }, "notification"); }

async function createEmployee(request, response, next) { try { assertEmployer(request); const { fullName, name, email, password, role, title, department } = request.body; const normalizedEmail = String(email || "").trim().toLowerCase(); if (!fullName && !name || !normalizedEmail || !password) throw new HttpError(400, "fullName, email, and password are required"); if (data.findOne("users", (user) => user.email === normalizedEmail)) throw new HttpError(409, "An account with this email already exists"); const bcrypt = require("bcryptjs"); const employee = data.insert("users", { companyId: request.user.companyId, fullName: fullName || name, name: fullName || name, email: normalizedEmail, role: "employee", title: title || role || "Employee", department: department || "General", status: "Active", teamId: "", passwordHash: await bcrypt.hash(password, 12) }, "employee"); send(response, publicUser(employee), 201); } catch (error) { next(error); } }
function listEmployees(request, response, next) { try { assertEmployer(request); send(response, data.list("users", request.user.companyId, (user) => user.role === "employee").map(publicUser)); } catch (error) { next(error); } }
function employee(request, response, next) { try { assertEmployer(request); send(response, publicUser(requireRecord("users", request.params.id, request.user.companyId))); } catch (error) { next(error); } }
async function updateEmployee(request, response, next) { try { assertEmployer(request); const current = requireRecord("users", request.params.id, request.user.companyId); const changes = { ...request.body }; delete changes.passwordHash; if (changes.email) changes.email = changes.email.trim().toLowerCase(); if (changes.password) { const bcrypt = require("bcryptjs"); changes.passwordHash = await bcrypt.hash(changes.password, 12); delete changes.password; } const updated = data.patch("users", current.id, request.user.companyId, changes); send(response, publicUser(updated)); } catch (error) { next(error); } }
function deleteEmployee(request, response, next) { try { assertEmployer(request); requireRecord("users", request.params.id, request.user.companyId); data.destroy("users", request.params.id, request.user.companyId); send(response, { id: request.params.id, deleted: true }); } catch (error) { next(error); } }

function list(collection, request, response, next) { try { let records = visible(collection, request); if (collection === "projects") records = records.map((record) => calculateProject(record, request.user.companyId)); if (collection === "teams") records = records.map((record) => calculateTeam(record, request.user.companyId)); send(response, records); } catch (error) { next(error); } }
function get(collection, request, response, next) { try { const record = requireRecord(collection, request.params.id, request.user.companyId); if (request.user.role === "employee" && !visible(collection, request, (item) => item.id === record.id).some((item) => item.id === record.id)) throw new HttpError(403, "You do not have access to this record"); send(response, collection === "projects" ? calculateProject(record, request.user.companyId) : collection === "teams" ? calculateTeam(record, request.user.companyId) : record); } catch (error) { next(error); } }
function createRecord(collection, prefix, request, response, next) { try { assertEmployer(request); const payload = { ...request.body, companyId: request.user.companyId }; if (collection === "tasks") { payload.status = status(payload.status) || "TODO"; payload.createdBy = request.user.id; payload.createdAt = new Date().toISOString(); payload.updatedAt = payload.createdAt; payload.assigneeId = payload.assigneeId || payload.assignedEmployeeId; } if (collection === "teams") { payload.memberIds = payload.memberIds || []; payload.memberRoles = payload.memberRoles || {}; } const record = data.insert(collection, payload, prefix); send(response, collection === "projects" ? calculateProject(record, request.user.companyId) : record, 201); } catch (error) { next(error); } }
function updateRecord(collection, request, response, next) { try { assertEmployer(request); const current = requireRecord(collection, request.params.id, request.user.companyId); const changes = { ...request.body }; if (collection === "tasks" && changes.status) { changes.status = status(changes.status); if (!changes.status) throw new HttpError(400, "Invalid task status"); } const updated = data.patch(collection, current.id, request.user.companyId, changes); send(response, collection === "projects" ? calculateProject(updated, request.user.companyId) : updated); } catch (error) { next(error); } }
function deleteRecord(collection, request, response, next) { try { assertEmployer(request); requireRecord(collection, request.params.id, request.user.companyId); data.destroy(collection, request.params.id, request.user.companyId); send(response, { id: request.params.id, deleted: true }); } catch (error) { next(error); } }

function updateTask(request, response, next) { try { const task = requireRecord("tasks", request.params.id, request.user.companyId); const requestedStatus = status(request.body.status); if (!requestedStatus) throw new HttpError(400, "Invalid task status"); if (request.user.role === "employee") { if (task.assignedEmployeeId !== request.user.id && task.assigneeId !== request.user.id) throw new HttpError(403, "Employees can only update assigned tasks"); if (!["TODO", "IN_PROGRESS", "DONE", "CHANGES_REQUESTED"].includes(requestedStatus)) throw new HttpError(403, "Employees cannot review or approve tasks"); } let nextStatus = requestedStatus; if (request.user.role === "employee" && requestedStatus === "DONE") nextStatus = "AWAITING_REVIEW"; if (request.user.role === "employer" && ["APPROVED", "CHANGES_REQUESTED"].includes(nextStatus) && task.status !== "AWAITING_REVIEW") throw new HttpError(400, "Tasks must be awaiting review"); const changes = { ...request.body, status: nextStatus, updatedAt: new Date().toISOString(), assignedEmployeeId: request.body.assignedEmployeeId || task.assignedEmployeeId || task.assigneeId, assigneeId: request.body.assignedEmployeeId || task.assigneeId || task.assignedEmployeeId }; const updated = data.patch("tasks", task.id, request.user.companyId, changes); if (nextStatus !== task.status) { const recipientId = request.user.role === "employee" ? request.user.companyId : task.assignedEmployeeId || task.assigneeId; createNotification(request.user.companyId, { recipientId, type: requestedStatus === "DONE" ? "task_completed" : "task_status_changed", message: requestedStatus === "DONE" ? "An employee completed a task" : `Task status changed to ${nextStatus}`, relatedTaskId: task.id, relatedProjectId: task.projectId, relatedEmployeeId: task.assignedEmployeeId || task.assigneeId }); } send(response, updated); } catch (error) { next(error); } }

function teamCreate(request, response, next) { try { assertEmployer(request); const members = request.body.members || []; const memberIds = request.body.memberIds || members.map((member) => member.employeeId); const memberRoles = { ...(request.body.memberRoles || {}) }; members.forEach((member) => { if (!member.employeeId || !teamRoles.includes(member.role) || member.role === "Custom Role" && !member.customRole) throw new HttpError(400, "Invalid team member role"); memberRoles[member.employeeId] = member.role === "Custom Role" ? member.customRole : member.role; }); if (new Set(memberIds).size !== memberIds.length) throw new HttpError(409, "Team members must be unique"); const team = data.insert("teams", { ...request.body, companyId: request.user.companyId, memberIds, memberRoles }, "team"); send(response, calculateTeam(team, request.user.companyId), 201); } catch (error) { next(error); } }
function teamUpdate(request, response, next) { try { assertEmployer(request); const current = requireRecord("teams", request.params.id, request.user.companyId); const changes = { ...request.body }; if (changes.members) { changes.memberIds = changes.members.map((member) => member.employeeId); changes.memberRoles = Object.fromEntries(changes.members.map((member) => [member.employeeId, member.role === "Custom Role" ? member.customRole : member.role])); } if (changes.memberIds && new Set(changes.memberIds).size !== changes.memberIds.length) throw new HttpError(409, "Team members must be unique"); const updated = data.patch("teams", current.id, request.user.companyId, changes); send(response, calculateTeam(updated, request.user.companyId)); } catch (error) { next(error); } }

function notifications(request, response, next) { try { const records = data.list("notifications", request.user.companyId, (item) => item.recipientId === request.user.id || item.recipientId === request.user.email || request.user.role === "employer" && item.recipientId === request.user.companyId); send(response, records); } catch (error) { next(error); } }
function unread(request, response, next) { try { const records = data.list("notifications", request.user.companyId, (item) => !item.read && (item.recipientId === request.user.id || item.recipientId === request.user.email)); send(response, records); } catch (error) { next(error); } }
function markRead(request, response, next) { try { const item = requireRecord("notifications", request.params.id, request.user.companyId); if (item.recipientId !== request.user.id && item.recipientId !== request.user.email) throw new HttpError(403, "Notification access denied"); send(response, data.patch("notifications", item.id, request.user.companyId, { read: true })); } catch (error) { next(error); } }
function readAll(request, response, next) { try { const items = data.list("notifications", request.user.companyId, (item) => item.recipientId === request.user.id || item.recipientId === request.user.email); items.forEach((item) => data.patch("notifications", item.id, request.user.companyId, { read: true })); send(response, { updated: items.length }); } catch (error) { next(error); } }
function deleteNotification(request, response, next) { try { const item = requireRecord("notifications", request.params.id, request.user.companyId); if (item.recipientId !== request.user.id && item.recipientId !== request.user.email) throw new HttpError(403, "Notification access denied"); data.destroy("notifications", item.id, request.user.companyId); send(response, { id: item.id, deleted: true }); } catch (error) { next(error); } }

module.exports = { createEmployee, listEmployees, employee, updateEmployee, deleteEmployee, list, get, createRecord, updateRecord, deleteRecord, updateTask, teamCreate, teamUpdate, notifications, unread, markRead, readAll, deleteNotification, taskStatuses, teamRoles };