const bcrypt = require("bcryptjs");
const data = require("../services/jsonStore");

const companyId = "company-demo";
const users = [
  { id: "sarah", companyId, fullName: "Sarah Johnson", name: "Sarah Johnson", email: "employer@nexaflow.demo", role: "employer", title: "CEO", department: "Executive", status: "Active", teamId: "executive", passwordHash: "$2b$10$IxhLA6SzP.YE80jeASBhDeSDIRdp/RqHx2mq/qkOO7OqRoAazfRza" },
  { id: "alex", companyId, fullName: "Alex Morgan", name: "Alex Morgan", email: "employee@nexaflow.demo", role: "employee", title: "Frontend Developer", department: "Engineering", status: "Active", teamId: "engineering", passwordHash: "$2b$10$bABrgbw/MnuZBNlPC/H2neufkRwulr3kHxF8Nt7VftWERMUE5X1Qu" },
  { id: "daniel", companyId, fullName: "Daniel Kim", name: "Daniel Kim", email: "daniel@nexaflow.demo", role: "employee", title: "Backend Developer", department: "Engineering", status: "Active", teamId: "engineering", passwordHash: "$2b$10$bABrgbw/MnuZBNlPC/H2neufkRwulr3kHxF8Nt7VftWERMUE5X1Qu" },
  { id: "maya", companyId, fullName: "Maya Chen", name: "Maya Chen", email: "maya@nexaflow.demo", role: "employee", title: "UI/UX Designer", department: "Design", status: "Active", teamId: "design", passwordHash: "$2b$10$bABrgbw/MnuZBNlPC/H2neufkRwulr3kHxF8Nt7VftWERMUE5X1Qu" },
  { id: "riley", companyId, fullName: "Riley Stone", name: "Riley Stone", email: "riley@nexaflow.demo", role: "employee", title: "Product Manager", department: "Product", status: "Away", teamId: "product", passwordHash: "$2b$10$bABrgbw/MnuZBNlPC/H2neufkRwulr3kHxF8Nt7VftWERMUE5X1Qu" },
  { id: "jordan", companyId, fullName: "Jordan Lee", name: "Jordan Lee", email: "jordan@nexaflow.demo", role: "employee", title: "Growth Lead", department: "Marketing", status: "Active", teamId: "marketing", passwordHash: "$2b$10$bABrgbw/MnuZBNlPC/H2neufkRwulr3kHxF8Nt7VftWERMUE5X1Qu" },
];
const projects = [
  { id: "website", companyId, name: "NexaFlow Website", description: "A clearer, faster marketing experience for modern teams.", status: "Active", startDate: "2026-07-01", deadline: "2026-08-30", leader: "riley", managerId: "riley", teamId: "engineering", participants: ["alex", "daniel", "maya"], memberIds: ["alex", "daniel", "maya"] },
  { id: "mobile", companyId, name: "Mobile Application", description: "Bring the workspace to every team member on the move.", status: "Active", startDate: "2026-07-15", deadline: "2026-09-12", leader: "riley", managerId: "riley", teamId: "engineering", participants: ["alex", "jordan"], memberIds: ["alex", "jordan"] },
  { id: "travel", companyId, name: "Travel Platform", description: "A flexible booking workflow for distributed teams.", status: "Active", startDate: "2026-06-15", deadline: "2026-09-05", leader: "riley", managerId: "riley", teamId: "product", participants: ["maya", "riley", "daniel"], memberIds: ["maya", "riley", "daniel"] },
];
const tasks = [
  { id: "auth", companyId, title: "Implement authentication", name: "Implement authentication", description: "Connect the sign-in flow.", projectId: "website", teamId: "engineering", assignedEmployeeId: "alex", assigneeId: "alex", createdBy: "sarah", status: "IN_PROGRESS", dueDate: "2026-08-25", createdAt: "2026-08-01", updatedAt: "2026-08-01" },
  { id: "dashboard", companyId, title: "Build dashboard components", name: "Build dashboard components", description: "Create reusable overview panels.", projectId: "website", teamId: "engineering", assignedEmployeeId: "alex", assigneeId: "alex", createdBy: "sarah", status: "IN_PROGRESS", dueDate: "2026-08-27", createdAt: "2026-08-01", updatedAt: "2026-08-01" },
  { id: "mobile-nav", companyId, title: "Fix mobile navigation", name: "Fix mobile navigation", description: "Polish the responsive drawer.", projectId: "mobile", teamId: "engineering", assignedEmployeeId: "alex", assigneeId: "alex", createdBy: "sarah", status: "AWAITING_REVIEW", dueDate: "2026-08-26", createdAt: "2026-08-01", updatedAt: "2026-08-01" },
  { id: "api-contract", companyId, title: "Document API contracts", name: "Document API contracts", description: "Capture service boundaries.", projectId: "travel", teamId: "engineering", assignedEmployeeId: "daniel", assigneeId: "daniel", createdBy: "sarah", status: "TODO", dueDate: "2026-09-02", createdAt: "2026-08-01", updatedAt: "2026-08-01" },
  { id: "design-review", companyId, title: "Share design review", name: "Share design review", description: "Review navigation prototypes.", projectId: "mobile", teamId: "design", assignedEmployeeId: "maya", assigneeId: "maya", createdBy: "sarah", status: "APPROVED", dueDate: "2026-08-22", createdAt: "2026-08-01", updatedAt: "2026-08-01" },
];
const teams = [{ id: "executive", companyId, name: "Executive", description: "Lead company vision.", leadId: "sarah", memberIds: ["sarah"], memberRoles: { sarah: "Team Lead" }, projectIds: ["website", "mobile", "travel"] }, { id: "engineering", companyId, name: "Engineering", description: "Build NexaFlow.", leadId: "daniel", memberIds: ["alex", "daniel"], memberRoles: { alex: "Frontend Developer", daniel: "Backend Developer" }, projectIds: ["website", "mobile"] }, { id: "design", companyId, name: "Product Design", description: "Shape the product.", leadId: "maya", memberIds: ["alex", "maya"], memberRoles: { alex: "Frontend Developer", maya: "UI/UX Designer" }, projectIds: ["website", "mobile"] }, { id: "product", companyId, name: "Product", description: "Connect needs to delivery.", leadId: "riley", memberIds: ["riley"], memberRoles: { riley: "Product Manager" }, projectIds: ["travel"] }];
const notifications = [{ id: "n1", companyId, recipientId: "alex", type: "task_assigned", message: "You were assigned a new task", relatedTaskId: "dashboard", relatedProjectId: "website", relatedEmployeeId: "alex", read: false, createdAt: new Date().toISOString() }, { id: "n2", companyId, recipientId: "sarah", type: "task_completed", message: "Alex Morgan completed a task", relatedTaskId: "mobile-nav", relatedProjectId: "mobile", relatedEmployeeId: "alex", read: false, createdAt: new Date().toISOString() }];
data.writeAll("companies", [{ id: companyId, name: "NexaFlow Demo Company", email: "employer@nexaflow.demo", size: "11-50", ownerId: "sarah" }]);
data.writeAll("users", users); data.writeAll("projects", projects); data.writeAll("tasks", tasks); data.writeAll("teams", teams); data.writeAll("notifications", notifications);
console.log("NexaFlow demo JSON data initialized");